#client = Client(
#    square_version='2023-08-16',
#    access_token=API_KEY,
#    environment='sandbox')

class Order:
    order_id = ''
    ongoing_order = False

    order_items = []
    
    def __init__(self):
        #self.menu = getMenu()
        pass

    def getMenu():
        pass

    
    # this should be loaded from square client api when Order is instantiated.
    menu =  {'objects': [{'created_at': '2023-09-04T22:29:03.341Z',
              'id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
              'is_deleted': False,
              'item_data': {'category_id': 'ZCQFIQVAJF73WI6Y7JJZRVME',
                            'description': 'A classic muffin.',
                            'description_html': '<p>A classic muffin.</p>',
                            'description_plaintext': 'A classic muffin.',
                            'ecom_visibility': 'UNINDEXED',
                            'is_archived': False,
                            'is_taxable': True,
                            'item_options': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX'},
                                             {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7'}],
                            'name': 'Muffin',
                            'product_type': 'REGULAR',
                            'skip_modifier_screen': False,
                            'variations': [{'created_at': '2023-09-04T22:29:03.341Z',
                                            'id': 'QHIFP5QQD373ZLO5P7FHGTCM',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'SNZDZT4YZ7ENIL5ETQDZC7UW'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'OEGNPQ66QGPCHDWMB6RYSPNQ'}],
                                                                    'name': 'Small, '
                                                                            'Blueberry',
                                                                    'ordinal': 0,
                                                                    'price_money': {'amount': 300,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Small '
                                                                           'Blueberry '
                                                                           'Muffin',
                                                                    'stockable': True,
                                                                    'track_inventory': False},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': 'JNYKOOGSGGF7XEKJBUNEK5WB',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'SNZDZT4YZ7ENIL5ETQDZC7UW'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'GFOYTNGKDCHL4QBFS74HM5G4'}],
                                                                    'name': 'Small, '
                                                                            'Banana '
                                                                            'Chocolate '
                                                                            'Chip',
                                                                    'ordinal': 1,
                                                                    'price_money': {'amount': 300,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Small '
                                                                           'BCC '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': '36X25BSZPXURAJEU7KETG6IV',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'SNZDZT4YZ7ENIL5ETQDZC7UW'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'PIIIOJ2M3NMRVIITWDTSMKAB'}],
                                                                    'name': 'Small, '
                                                                            'Radish',
                                                                    'ordinal': 2,
                                                                    'price_money': {'amount': 300,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Small '
                                                                           'Radish '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:27:44.646Z',
                                            'id': 'CZYCQBFTH54KTQDRHQQA5PHH',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'EJTDKKYZEBODWAF7G3GXMV5Z'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'OEGNPQ66QGPCHDWMB6RYSPNQ'}],
                                                                    'name': 'Medium, '
                                                                            'Blueberry',
                                                                    'ordinal': 3,
                                                                    'price_money': {'amount': 400,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Medium '
                                                                           'Blueberry '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': 'NIBVSCGUB6CT4VGZPBPGCHUU',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'EJTDKKYZEBODWAF7G3GXMV5Z'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'GFOYTNGKDCHL4QBFS74HM5G4'}],
                                                                    'name': 'Medium, '
                                                                            'Banana '
                                                                            'Chocolate '
                                                                            'Chip',
                                                                    'ordinal': 4,
                                                                    'price_money': {'amount': 400,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Medium '
                                                                           'Radish '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': 'IN5G7QOFNW3KPGA6LACUCY2W',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'EJTDKKYZEBODWAF7G3GXMV5Z'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'PIIIOJ2M3NMRVIITWDTSMKAB'}],
                                                                    'name': 'Medium, '
                                                                            'Radish',
                                                                    'ordinal': 5,
                                                                    'price_money': {'amount': 400,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Medium '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:27:44.646Z',
                                            'id': 'I7VXGGKOINY3XTX5O3BIACMD',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'ZBOKKLLI46RJ6BESQKI6MTCB'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'OEGNPQ66QGPCHDWMB6RYSPNQ'}],
                                                                    'name': 'Large, '
                                                                            'Blueberry',
                                                                    'ordinal': 6,
                                                                    'price_money': {'amount': 500,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Large '
                                                                           'Blueberry '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': 'P742FSUKGSR4DIU42ZRDG3HP',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'ZBOKKLLI46RJ6BESQKI6MTCB'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'GFOYTNGKDCHL4QBFS74HM5G4'}],
                                                                    'name': 'Large, '
                                                                            'Banana '
                                                                            'Chocolate '
                                                                            'Chip',
                                                                    'ordinal': 7,
                                                                    'price_money': {'amount': 500,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Large '
                                                                           'BCC '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283},
                                           {'created_at': '2023-09-06T15:32:32.283Z',
                                            'id': 'EHHE672IV5WFDTMIYAEFOOD3',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'ZX2MBU6L2N3K3KV3NDJP5GBQ',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'ZBOKKLLI46RJ6BESQKI6MTCB'},
                                                                                           {'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'PIIIOJ2M3NMRVIITWDTSMKAB'}],
                                                                    'name': 'Large, '
                                                                            'Radish',
                                                                    'ordinal': 8,
                                                                    'price_money': {'amount': 500,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Large '
                                                                           'Radish '
                                                                           'Muffin',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:32:32.283Z',
                                            'version': 1694014352283}],
                            'visibility': 'PRIVATE'},
              'present_at_all_locations': True,
              'type': 'ITEM',
              'updated_at': '2023-09-06T15:32:32.283Z',
              'version': 1694014352283},
             {'created_at': '2023-09-04T22:29:16.262Z',
              'id': 'MKYIBHNABLVT4UQNIRUHGIY7',
              'is_deleted': False,
              'item_data': {'category_id': 'ZCQFIQVAJF73WI6Y7JJZRVME',
                            'ecom_visibility': 'UNINDEXED',
                            'is_archived': False,
                            'is_taxable': True,
                            'item_options': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX'}],
                            'name': 'Coffee',
                            'product_type': 'REGULAR',
                            'skip_modifier_screen': False,
                            'variations': [{'created_at': '2023-09-04T22:29:16.262Z',
                                            'id': '4EWWXLTFINIWPH6XSZ7PR7UB',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'MKYIBHNABLVT4UQNIRUHGIY7',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'SNZDZT4YZ7ENIL5ETQDZC7UW'}],
                                                                    'location_overrides': [{'location_id': 'LETE3KSW0H1RB',
                                                                                            'track_inventory': False}],
                                                                    'name': 'Small',
                                                                    'ordinal': 0,
                                                                    'price_money': {'amount': 200,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Small '
                                                                           'Coffee',
                                                                    'stockable': True,
                                                                    'track_inventory': False},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:31:08.493Z',
                                            'version': 1694014268493},
                                           {'created_at': '2023-09-06T15:31:08.493Z',
                                            'id': '763UAVMAG3JKNNWKKZH46WEZ',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'MKYIBHNABLVT4UQNIRUHGIY7',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'EJTDKKYZEBODWAF7G3GXMV5Z'}],
                                                                    'name': 'Medium',
                                                                    'ordinal': 1,
                                                                    'price_money': {'amount': 250,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Medium '
                                                                           'Coffee',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:31:08.493Z',
                                            'version': 1694014268493},
                                           {'created_at': '2023-09-06T15:31:08.493Z',
                                            'id': 'JHHYV2RFNB3K2DJGR7OM2RCZ',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'MKYIBHNABLVT4UQNIRUHGIY7',
                                                                    'item_option_values': [{'item_option_id': 'ZWGRHED6ZO7ZJU5HKZRI6XEX',
                                                                                            'item_option_value_id': 'ZBOKKLLI46RJ6BESQKI6MTCB'}],
                                                                    'name': 'Large',
                                                                    'ordinal': 2,
                                                                    'price_money': {'amount': 275,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Large '
                                                                           'Coffee',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:31:08.493Z',
                                            'version': 1694014268493}],
                            'visibility': 'PRIVATE'},
              'present_at_all_locations': True,
              'type': 'ITEM',
              'updated_at': '2023-09-06T15:31:08.493Z',
              'version': 1694014268493},
             {'created_at': '2023-09-04T22:29:26.182Z',
              'id': 'R7WYKI4QUSJPQFLFVIWKM5D6',
              'is_deleted': False,
              'item_data': {'category_id': 'ZCQFIQVAJF73WI6Y7JJZRVME',
                            'ecom_visibility': 'UNINDEXED',
                            'is_archived': False,
                            'is_taxable': True,
                            'item_options': [{'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7'}],
                            'name': 'Danish',
                            'product_type': 'REGULAR',
                            'skip_modifier_screen': False,
                            'variations': [{'created_at': '2023-09-04T22:29:26.182Z',
                                            'id': 'U3PUMOAAS5O6TJ6GAIXUVDAY',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'R7WYKI4QUSJPQFLFVIWKM5D6',
                                                                    'item_option_values': [{'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'OEGNPQ66QGPCHDWMB6RYSPNQ'}],
                                                                    'location_overrides': [{'location_id': 'LETE3KSW0H1RB',
                                                                                            'track_inventory': False}],
                                                                    'name': 'Blueberry',
                                                                    'ordinal': 0,
                                                                    'price_money': {'amount': 400,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Blueberry '
                                                                           'Danish',
                                                                    'stockable': True,
                                                                    'track_inventory': False},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:30:22.994Z',
                                            'version': 1694014222994},
                                           {'created_at': '2023-09-06T15:30:22.994Z',
                                            'id': 'K57VNFAJVBSIYWAJUAA4Z6U2',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'R7WYKI4QUSJPQFLFVIWKM5D6',
                                                                    'item_option_values': [{'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'GFOYTNGKDCHL4QBFS74HM5G4'}],
                                                                    'name': 'Banana '
                                                                            'Chocolate '
                                                                            'Chip',
                                                                    'ordinal': 1,
                                                                    'price_money': {'amount': 350,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'BCC '
                                                                           'Danish',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:30:22.994Z',
                                            'version': 1694014222994},
                                           {'created_at': '2023-09-06T15:30:22.994Z',
                                            'id': 'R63UU67FQB6LHZ57W5GPROSR',
                                            'is_deleted': False,
                                            'item_variation_data': {'item_id': 'R7WYKI4QUSJPQFLFVIWKM5D6',
                                                                    'item_option_values': [{'item_option_id': 'RQJ3LENJVKXIAWXRV5W4CSO7',
                                                                                            'item_option_value_id': 'PIIIOJ2M3NMRVIITWDTSMKAB'}],
                                                                    'name': 'Radish',
                                                                    'ordinal': 2,
                                                                    'price_money': {'amount': 300,
                                                                                    'currency': 'USD'},
                                                                    'pricing_type': 'FIXED_PRICING',
                                                                    'sellable': True,
                                                                    'sku': 'Radish '
                                                                           'Danish',
                                                                    'stockable': True},
                                            'present_at_all_locations': True,
                                            'type': 'ITEM_VARIATION',
                                            'updated_at': '2023-09-06T15:30:22.994Z',
                                            'version': 1694014222994}],
                            'visibility': 'PRIVATE'},
              'present_at_all_locations': True,
              'type': 'ITEM',
              'updated_at': '2023-09-06T15:30:22.994Z',
              'version': 1694014222994}]}
